status = {
    'freddy': 0, 
    'bonnie': 0, 
    'chica': 0, 
    'foxy': 0, 
    't freddy': 0, 
    't bonnie': 0, 
    't chica': 0, 
    't foxy': 0, 
    'freddy': 0, 
    'freddy': 0, 
    'freddy': 0, 
    'freddy': 0, 
    'freddy': 0, 
    'freddy': 0, 
    'freddy': 0, 
    'freddy': 0, 
    'freddy': 0, 
}